---@enum DriverStatus
DriverStatus = {
  WAITING_FOR_DELIVERY = 0,
  WAITING_FOR_ROUTE_INIT = 1,
  COLLECTING_TRUCK = 2,
  COLLECTING_TRAILER = 3,
  DELIVERING_TRAILER = 4,
  RETURNING_TO_DEPOT = 5,
  RETURNING_TRUCK = 6,
  SPEAKING_WITH_MANAGER = 7
}
